version: '3'

services:
  postgres:
    image: makstreid/trenerfront_postgres:latest
    container_name: trenerfront_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=interview_prep
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - trenerfront_network

  pgadmin:
    image: makstreid/trenerfront_pgadmin:latest
    container_name: trenerfront_pgadmin
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - trenerfront_network

networks:
  trenerfront_network:
    driver: bridge

volumes:
  postgres_data:
